# Generated by Django 5.0 on 2024-01-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='working',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
